name: Harold's Release Notifications
description: Post a message in Slack to say the deployment is initiated, create a release note, and post that note in Slack. Automates JIRA ticket status movement.
inputs:
  git-token:
    description: GitHub Personal Access Token used to checkout Harold
    required: true
  channel:
    description: Slack channel that Harold posts in
    required: true
  uri:
    description: URI to retrieve the sha of the releasing service
    required: true
  slack-token:
    description: Slack authorization token
    required: true
  repo:
    description: GitHub repository that is being released
    required: true
  jira-token:
    description: JIRA authorization token
    required: true
  jira-user:
    description: JIRA username
    required: true
  jira-uri:
    description: JIRA uri
    required: true
  before-sha:
    description: SHA of the previous version
    required: true
  head-sha:
    description: SHA of the HEAD
    required: true
  release-sha:
    description: SHA of the releasing version
    required: true
  failure-webhook:
    description: The webhook to trigger if the deployment fails.
    required: true
  success-webhook:
    description: The webhook to trigger if the deployment succeeds.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.head-sha }}
        fetch-depth: 0
    - name: Set up Ruby 2.7.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
    - run: |
        git log --graph --abbrev-commit
        git clone https://${{ inputs.git-token }}@github.com/oncarrot/harold.git
        cd harold
        gem build harold.gemspec
        gem install harold
        harold sing -c ${{ inputs.channel }} -t ${{ inputs.slack-token }} -r ${{ inputs.repo }}
        mkdir tmp || echo "tmp/ already exists"
        harold note -b ${{ inputs.before-sha }} -f ${{ inputs.failure-webhook }} -g "https://github.com/${{ inputs.repo }}" -o tmp/ -r ${{ inputs.release-sha }} -s ${{ inputs.success-webhook }} -u ${{ inputs.uri }} -G ${{ inputs.git-token }} -J ${{ inputs.jira-uri }} -T ${{ inputs.jira-token }} -U ${{ inputs.jira-user }}
        harold sing -c ${{ inputs.channel }} -t ${{ inputs.slack-token }} -f tmp/release_note.txt -r ${{ inputs.repo }}
      shell: bash
